### ISSUE TITLE
Valid RSA public key not recognized by OpenSSL::PKey::RSA

### ISSUE THREAD

**Issue by sobstel** [ruby/openssl#106]
```
require 'openssl'

public_key = OpenSSL::PKey::RSA.new <<-PEM
-----BEGIN CERTIFICATE-----
MIIC8DCCAdigAwIBAgIJO8X5q8TVB+WXMA0GCSqGSIb3DQEBBQUAMB8xHTAbBgNV
BAMTFGFwcGpvYnMuZXUuYXV0aDAuY29tMB4XDTE3MDEyMzA5NTMyNFoXDTMwMTAw
MjA5NTMyNFowHzEdMBsGA1UEAxMUYXBwam9icy5ldS5hdXRoMC5jb20wggEiMA0G
CSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDTE91uSKtBmUJfYRMZYzUJz3U55pY7
9JBd0y7hHUxuSObqvtVp6p5VLXrB51caGLuqhb+egm7CuVu++jX3am7E0I26tZ5Z
wqtZR3tO4GIsqILlTy5Oa6i8y9bp4SEm8rauBZ2t5WZonxGOJoqa8yegTbXvJl1O
/sw3LPhhPHezBASH26Y6x7cNNdOaPgP+OUR8vGTgia7x5pGg9eFKONIBWBlMT+De
QJsWoQo8ZO6go6aIYPKWx3cI893Yjm8mxQ9otq3kfkBaxWwSc6g4DEUQSPLAE7XB
RoZ2PtqN58a5MglHh6ZCKTxfEQDq6ulIoF9W9vs9Dm0YNEDYjVX4nh5XAgMBAAGj
LzAtMAwGA1UdEwQFMAMBAf8wHQYDVR0OBBYEFIniwZ2gAWNoYGTtVuEtd6wqPp3X
MA0GCSqGSIb3DQEBBQUAA4IBAQB3mnP/P0NpxoZgo8t3R5LgBoLhgZSBDH4Pt/UG
kqWIwP4Up2PBqL4SkfWa2VA0S3tt8EnFn21UbjzvH5oRVtlcYPHjwZrckk+oumUU
c7UR0E6t7FKEeeYdrVTy25gTW728vexqX8RYkZLIXPPJ88QA+iDcNALZqUQl74V3
aoUNUA6hWsd7AjgtrXmWka4YxLyYsU6i1hwhSGG9rSasy0vCVXi1FtDr6FoijHGj
o1JLMAh8zmXHVehWxVaEfWB4zkSzycB5AY6naVr8fvr6sD8QfpL7gvT3UnbF2Egn
BmGHJgrKcxM9hBjRYUSGpX9lRBWT54hQdFP1iNUeEtUAvr/5
-----END CERTIFICATE-----
PEM
```

results in

```
git:jwt-rs256 ❯ ruby test.rb                                                                                                                          
test.rb:3:in `initialize': Neither PUB key nor PRIV key: nested asn1 error (OpenSSL::PKey::RSAError)
	from test.rb:3:in `new'
	from test.rb:3:in `<main>'
```

ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin16]

**Comment by tarcieri** [comment]
That's a certificate, not a key. You need to parse it with OpenSSL::X509::Certificate: https://ruby-doc.org/stdlib-1.9.3/libdoc/openssl/rdoc/OpenSSL/X509/Certificate.html
