### ISSUE TITLE
Not able to create CSR with more than 1 subjectAltName

### ISSUE THREAD

**Issue by ernestothorp** [ruby/openssl#39]
I've tried to create a CSR, however the Name parsing fails

```
2.1.0 :035 > s="/C=US/ST=New York/L=New York/O=End Point/OU=Hosting Team/CN=*.my-primary-domain.com/emailAddress=administrative-address@my-primary-domain.com/subjectAltName=DNS.1=secondary-domain.com,DNS.2=www.secondary-domain.com,DNS.3=*.other-domain.com"
 => "/C=US/ST=New York/L=New York/O=End Point/OU=Hosting Team/CN=*.my-primary-domain.com/emailAddress=administrative-address@my-primary-domain.com/subjectAltName=DNS.1=secondary-domain.com,DNS.2=www.secondary-domain.com,DNS.3=*.other-domain.com"
2.1.0 :036 > OpenSSL::X509::Name.parse s
OpenSSL::X509::NameError: invalid field name
    from /Users/ernesto/.rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/openssl/x509.rb:149:in `each'
    from /Users/ernesto/.rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/openssl/x509.rb:149:in `initialize'
    from /Users/ernesto/.rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/openssl/x509.rb:149:in `new'
    from /Users/ernesto/.rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/openssl/x509.rb:149:in `parse_openssl'
    from (irb):36
    from /Users/ernesto/.rvm/rubies/ruby-2.1.0/bin/irb:11:in `<main>'
```

Changing the equal sign for a colon only changes the error

```
2.1.0 :037 > s="/C=US/ST=New York/L=New York/O=End Point/OU=Hosting Team/CN=*.my-primary-domain.com/emailAddress=administrative-address@my-primary-domain.com/subjectAltName=DNS.1:secondary-domain.com,DNS.2:www.secondary-domain.com,DNS.3:*.other-domain.com"
 => "/C=US/ST=New York/L=New York/O=End Point/OU=Hosting Team/CN=*.my-primary-domain.com/emailAddress=administrative-address@my-primary-domain.com/subjectAltName=DNS.1:secondary-domain.com,DNS.2:www.secondary-domain.com,DNS.3:*.other-domain.com"
2.1.0 :038 > OpenSSL::X509::Name.parse s
TypeError: no implicit conversion of nil into String
    from /Users/ernesto/.rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/openssl/x509.rb:149:in `each'
    from /Users/ernesto/.rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/openssl/x509.rb:149:in `initialize'
    from /Users/ernesto/.rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/openssl/x509.rb:149:in `new'
    from /Users/ernesto/.rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/openssl/x509.rb:149:in `parse_openssl'
    from (irb):38
    from /Users/ernesto/.rvm/rubies/ruby-2.1.0/bin/irb:11:in `<main>'
```

With the same subject I'm able to generate a CSR with the openssl command line

```
$ openssl req -new -key globo.key -sha256 -nodes -subj '/C=US/ST=New York/L=New York/O=End Point/OU=Hosting Team/CN=*.my-primary-domain.com/emailAddress=administrative-address@my-primary-domain.com/subjectAltName=DNS.1:secondary-domain.com,DNS.2:www.secondary-domain.com,DNS.3:*.other-domain.com'
-----BEGIN CERTIFICATE REQUEST-----
MIIDYTCCAkkCAQAwggEaMQswCQYDVQQGEwJVUzERMA8GA1UECAwITmV3IFlvcmsx
ETAPBgNVBAcMCE5ldyBZb3JrMRIwEAYDVQQKDAlFbmQgUG9pbnQxFTATBgNVBAsM
DEhvc3RpbmcgVGVhbTEgMB4GA1UEAwwXKi5teS1wcmltYXJ5LWRvbWFpbi5jb20x
OzA5BgkqhkiG9w0BCQEWLGFkbWluaXN0cmF0aXZlLWFkZHJlc3NAbXktcHJpbWFy
eS1kb21haW4uY29tMVswWQYDVR0RDFJETlMuMTpzZWNvbmRhcnktZG9tYWluLmNv
bSxETlMuMjp3d3cuc2Vjb25kYXJ5LWRvbWFpbi5jb20sRE5TLjM6Ki5vdGhlci1k
b21haW4uY29tMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAsnIx3UNQ
lh4iR4bNIVBNNeJ9Vdy1nf0JU0E7lmYWCefePK+id6HPqzV6cduBhV4lbuHURmew
ni2Bci8IWNeqF/3bab5PG4D2VA4x0b2YHZrcxgAW81OjwOCMqSE2tAWNu3+5Jj4Y
J3TY+ebfsP3BRITXibFRsEgWDTsYTZuU77MB5jqhFO5FoR1OuMuagJtMd9V+vsRt
iIspAP3ZZCB+lEkb5E+0SgDBFGxTMGZCJ4iUZVtDP3NhYz3mfxM6rF6TWY51OV5l
RMyzrpauUEqgzEfAKEep4PEt+yIp1KyCwyyslZRo8dAzAPj39M3XgS11PNbdsiy+
6As0/9Qsv/8AlQIDAQABoAAwDQYJKoZIhvcNAQELBQADggEBAKhGNL1Y69fqsvml
rajc5qOzPSmPGiwrFOyJon4leeqbIoEK4OqyN3ujLPVJPqhyF8r7BHTTucxGq+RA
nFcN9OgAsxF61A6Uz2Ip0iDHYyBpPyjznz+3CnmbRgAdwv51FUBG3GMrceBx/cwx
YrRc6XukGA+J0YeGtOxmc23ns1wvrtBkjuCWDN0YwH4Yq8EwaFz4pIbwU8VHjrq0
SsBEjKe1Q6v2m+0cfz3uztQ0aEs4OCCX/ZM8VPfKzn5V7Yq4pLp2YS1gDXtBeAFQ
m5NFUvR+G4JAo+w6r/6VVcl2pXNag7o4fjY346SkrP4yjDccebZQKLekuQ+bbZQL
jPJUNY4=
-----END CERTIFICATE REQUEST-----
```

This is not supported yet, or it's an error?

**Comment by dkam** [comment]
I create them like this: 

````
extension = OpenSSL::X509::ExtensionFactory.new.create_extension(
  "subjectAltName",
  domains.map {|domain| "DNS:#{domain}" }.join(", "),
  false
)
csr.add_attribute OpenSSL::X509::Attribute.new(
  "extReq",
  OpenSSL::ASN1::Set.new(
    [OpenSSL::ASN1::Sequence.new([extension])]
  )
)
```

**Comment by rhenium** [comment]
Subject alternative name is an X.509v3 extension and is not part of the distinguished name.

However, OpenSSL::X509::NameError was raised due to a different bug. #144 fixes this.
