### ISSUE TITLE
Unable to generate an  x509v3 CRL number extension to add to  a crl

### ISSUE THREAD

**Issue by nrh3** [ruby/openssl#660]
I'm doing a simple CA.    I would like to be able to number the CRLs.   This looks like it should be possible, but....

(crl already made, otherwise ready for signing):

`ext_factory = OpenSSL::X509::ExtensionFactory.new
=> #<OpenSSL::X509::ExtensionFactory:0x00000008066b7480 @config=nil>
[12] pry(#<CertificateAuthority>)> ext_factory.crl = crl
=> #<OpenSSL::X509::CRL:0x00000008067a2048>
[13] pry(#<CertificateAuthority>)> crl_number_extension = ext_factory.create_extension('crlNumber', crl_number.to_s, false)
OpenSSL::X509::ExtensionError: crlNumber = 12345: extension setting not supported
from /usr/local/lib/ruby/3.1/openssl/x509.rb:22:in `create_ext'
[14] pry(#<CertificateAuthority>)> crl_number_extension = ext_factory.create_extension('2.5.29.20.', crl_number.to_s, false)
OpenSSL::X509::ExtensionError: unknown OID `2.5.29.20.'
from /usr/local/lib/ruby/3.1/openssl/x509.rb:22:in `create_ext'`

Really a bug?    My own ignorance?   Thanks for any help....

**Comment by nrh3** [comment]
Still not sure if this was a bug or not, but I got around it by avoiding OpenSSL::X509::ExtensionFactory and just using crl.add_extension(OpenSSL::X509::Extension.new("crlNumber", "81768", false))
